seed_everything: 2023

trainer:
  #resume_from_checkpoint: /root/autodl-tmp/output-models/pt2t/pt2t-large-train_2_train_test/last.ckpt
  logger: true
  default_root_dir: /root/autodl-tmp/output-models/pt2t/fnlp-bart-base
  accelerator: gpu
  devices: 8
  strategy: ddp
  accumulate_grad_batches: 1
  precision: 16
  check_val_every_n_epoch: 10
  max_steps: 20000
  gradient_clip_val: 0.5
  callbacks:
    - class_path: rlt2t.callbacks.save_pretrained_model_callback.SavePretrainedModelCallback
      init_args:
        save_top_k: 2 # save k best models (determined by above metric)
        monitor: 'val/bleu4'
        mode: 'max'
        save_last: True # additionaly always save model from last epoch
        verbose: True
        dirpath: ${trainer.default_root_dir}
        filename: "epoch_{epoch}"
        auto_insert_metric_name: False
        every_n_epochs: 10
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  class_path: rlt2t.models.t2t_model.T2TModel
  init_args:
    init_model: "/root/autodl-tmp/pmodels/fnlp-bart-base"
    # 2e-5
    lr: 8e-5
    weight_decay: 0.01
    warmup_step: 1000
    max_iters: 10000
    min_lr: 2e-5

data:
  class_path: rlt2t.datasets.t2t_pretrain_datamodule.T2TPretrainDataModule
  init_args:
    data_dir: data/pt2t/train_2_train_test
    # large 64; base 256; xlarge: 32
    batch_size: 64
    max_source_length: 256
    max_target_length: 96
    start_idx: 106
    num_words: 1800
    eos_id: 105
    noise_density: 0.15
    mean_noise_span_length: 3.0
    num_workers: 1
