seed_everything: 842

trainer:
  resume_from_checkpoint: /root/autodl-tmp/output-models/uer/bart-large-1-rank/last.ckpt
  logger: true
  default_root_dir: /root/autodl-tmp/output-models/uer/bart-large-1-rank
  accelerator: gpu
  devices: 2
  strategy: ddp
  accumulate_grad_batches: 3
  # 16
  precision: 16
  #check_val_every_n_epoch: 1
  val_check_interval: 1000
  max_steps: 80000
  # bart gradient_clip_val: 0.5, T5: None
  gradient_clip_val: 0.5
  callbacks:
#    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
#      init_args:
#        swa_lrs: 1e-5
#        swa_epoch_start: 1
#        annealing_epochs: 10
    - class_path: rlt2t.callbacks.save_pretrained_model_callback.SavePretrainedModelCallback
      init_args:
        save_top_k: 3 # save k best models (determined by above metric)
        monitor: 'val/m_score'
        mode: 'max'
        save_last: True # additionaly always save model from last epoch
        verbose: True
        dirpath: ${trainer.default_root_dir}
        filename: "epoch_{epoch}_{step}"
        auto_insert_metric_name: False
        #every_n_epochs: 1
        every_n_train_steps: 1000
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  class_path: rlt2t.models.t2t_rank_model.T2TRankModel
  init_args:
    init_model: "/root/autodl-tmp/output-models/uer/bart-large-1-rank/base"
    # bart 2e-5; t5 1e-3
    lr: 2e-5
    weight_decay: 0.01
    warmup_step: 5
    max_iters: 5000
    rank_start_iters: 0
    rank_loss_rate: 0.2
    delay_alpha: 0.95
    # 0.5
    rdrop_alpha: 2.0
    rdrop_start_steps: 0
    dropout_rate: 0.15
    min_lr: 1e-5

data:
  class_path: rlt2t.datasets.t2t_rank_datamodule.T2TRankDataModule
  init_args:
    data_dir: data/t2t/train_2_train
    # bart-large: 32; bart-base: 256; xl: 16
    batch_size: 8
    max_source_length: 256
    max_target_length: 96
    start_idx: 106
    num_words: 1800
    eos_id: 105
    num_workers: 1
    augment_text: True
    port: 9549
    use_rank: True
