deepspeed --num_gpus=1 tasks/sft-t2t/run_t2t.py \
      --deepspeed tasks/sft-t2t/ds_config.json \
      --model_name_or_path /root/autodl-tmp/models/IDEA-CCNL/Randeng-T5-784M \
      --do_train \
      --do_eval \
      --train_file /root/autodl-tmp/data/train.json \
      --validation_file /root/autodl-tmp/data/test.json \
      --text_column text \
      --summary_column summary \
      --source_prefix "" \
      --output_dir /root/autodl-tmp/output-models/sft-t2t \
      --text_map_start_idx 3 \
      --text_map_num_words 6100 \
      --max_eval_samples 4 \
      --max_train_samples 20 \
      --per_device_train_batch_size 2 \
      --per_device_eval_batch_size 4 \
      --num_train_epochs 5 \
      --learning_rate 5e-5 \
      --weight_decay 0.0 \
      --max_steps 400 \
      --warmup_steps 100 \
      --lr_scheduler_type linear \
      --logging_steps 20 \
      --save_steps 100 \
      --save_total_limit 2 \
      --overwrite_output_dir \
      --predict_with_generate \
      --fp16
